### ISSUE TITLE
"" attributes instead of : "0_no_attributes"

### ISSUE THREAD

**Issue by dpny518** [kosmosmo/NFT_Art_Generator#5]
In attributes, we get some attributes with "" instead of  : "0_no_attributes"
 
   "01_Backgroud": ""
 instead of 
  "01_Backgroud": "0_no_attributes"

**Comment by kosmosmo** [comment]
which step which file?

**Comment by dpny518** [comment]
There was in hidden pngs like ._name.png
I removed them all and it works now
